services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pg
      POSTGRES_DB: data
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  node:
    depends_on: 
      - postgres
    build: 
      dockerfile: ./dockerfiles/api/dockerfile
      context: .
    network_mode: host # container thinks it's my local machine
    volumes:
      - .:/workspaces/root
    command: >
      sh -c " cd /workspaces/root/data-app-api && 
      npm run db:init &&
      npm start "
  python:
    depends_on: 
      - postgres 
      - node
    build: 
      dockerfile: ./dockerfiles/nlp/dockerfile
      context: .
    network_mode: host # container thinks it's my local machine
    volumes:
      - .:/workspaces/root
    command: sh -c "python3 --version"

volumes:
  postgres-data: 
