services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pg
      POSTGRES_DB: data
    ports:
      - "5432:5432"
    expose:
      - "5432" 
    volumes:
      - postgres-data:/var/lib/postgresql/data
  node:
    depends_on: 
      - postgres
    build: 
      dockerfile: ./dockerfiles/api/dockerfile
      context: .
    ports:
      - "3031:3031" 
    volumes:
      - ./:/workspaces
    command: >
      sh -c " 
      cd /workspaces/data-app-api && 
      npm i &&
      npm run db:init &&
      npm start"
  # python:
  #   depends_on: 
  #     - postgres 
  #     - node
  #   build: 
  #     dockerfile: ./dockerfiles/nlp/dockerfile
  #     context: .
  #   ports:
  #     - "8086:8086"
  #   volumes:
  #     - .:/workspaces/root
  #   command: sh -c " cd /workspaces/root/data-app-nlp &&
  #     python -u -m src"

volumes:
  postgres-data: 
